### PR TITLE
Bump static module dependency to fix security problem

### PR DESCRIPTION
**Pull request by arj03**
Fixes:

Moderate        Sandbox Breakout / Arbitrary Code Execution                   
                                                                                
  Package         static-eval                                                   
                                                                                
  Patched in      >=2.0.0                                                       
                                                                                
  Dependency of  .....                                                 
                                                                                
  Path            .... > read-directory > static-module > static-eval  
                                                                                
  More info       https://nodesecurity.io/advisories/548

### CODE REVIEW

**Comment by arj03** [comment]
@sethvincent we have a couple of projects that depend on read-dir and would really like to have this fixed. Any change you can have a look? Thanks

**Comment by christianbundy** [comment]
cc: @yoshuawuyts, any chance you could help us with this?

**Comment by sethvincent** [comment]
thanks! sorry, just noticed this pr was open.

**Comment by christianbundy** [comment]
@sethvincent Thanks a lot! Would you be able to `npm publish` this as 3.0.1 as well? Really appreciate your help on this.

**Comment by sethvincent** [comment]
📦 published as 3.0.1

**Pull request merged**
